package com.glassgo.platform.iam.domain.model.entities;

import com.glassgo.platform.iam.domain.model.valueobjects.Roles;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.With;

import java.util.List;

/**
 * Role Entity in the Identity and Access Management (IAM) bounded context.
 * <p>
 * This entity represents a role assigned to users, defining their permissions and access levels
 * within the system. Roles are value-based entities that encapsulate authorization logic,
 * ensuring that users can only perform actions permitted by their assigned roles.
 * </p>
 * <p>
 * Key characteristics:
 * - Roles are immutable in their name but can be associated with users.
 * - Provides factory methods for creating and validating roles.
 * - Enforces domain invariants, such as defaulting to ROLE_USER if no roles are specified.
 * </p>
 *
 * @see Roles
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@With
public class Role {
    /**
     * The unique identifier of the role, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the role, represented as an enumeration value.
     * Defines the type of role (e.g., ROLE_USER, ROLE_ADMIN).
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private Roles name;

    /**
     * Constructs a new Role with the specified name.
     * The ID will be auto-generated upon persistence.
     *
     * @param name the enumeration value representing the role name
     */
    public Role(Roles name) {
        this.name = name;
    }

    /**
     * Get the name of the role as a string
     * @return the name of the role as a string
     */
    public String getStringName() {
        return name.name();
    }

    /**
     * Get the default role
     * @return the default role
     */
    public static Role getDefaultRole() {
        return new Role(Roles.ROLE_USER);
    }

    /**
     * Get the role from its name
     * @param name the name of the role
     * @return the role
     */
    public static Role toRoleFromName(String name) {
        return new Role(Roles.valueOf(name));
    }

    /**
     * Validate the role set
     * <p>
     *     This method validates the role set and returns the default role if the set is empty.
     * </p>
     * @param roles the role set
     * @return the role set
     */
    public static List<Role> validateRoleSet(List<Role> roles) {
        if (roles == null || roles.isEmpty()) {
            return List.of(getDefaultRole());
        }
        return roles;
    }

}
